apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  {{- $name := "{{ .app.metadata.name }}" }}
  {{- $syncStatus := "{{ .app.status.sync.status }}" }}
  {{- $repoURL := "{{ .app.spec.source.repoURL }}" }}
  {{- $startedAt := "{{ .app.status.operationState.startedAt }}" }}
  {{- $finishedAt := "{{ .app.status.operationState.finishedAt }}" }}
  {{- $message := "{{ .app.status.operationState.message }}" }}
  {{- $revision := "{{ .app.status.sync.revision }}" }}
  {{- $argocdUrl := "{{ .context.argocdUrl }}" }}
  {{- $healthStatus := "{{ .app.status.health.status }}" }}
  service.telegram: |
    token: $telegram-token
  template.app-created: |
    email:
      subject: Application {{ $name }} has been created.
    message: Application {{ $name }} has been created.
    teams:
      title: Application {{ $name }} has been created.
  template.app-deleted: |
    email:
      subject: Application {{ $name }} has been deleted.
    message: Application {{ $name }} has been deleted.
    teams:
      title: Application {{ $name }} has been deleted.
  template.app-deployed: |
    email:
      subject: New version of an application {{ $name }} is up and running.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{ $name }} is now running new version of deployments manifests.
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link":"{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#18be52",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{ $syncStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          },
          {
            "title": "Revision",
            "value": "{{ $revision }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ $syncStatus }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        },
        {
          "name": "Revision",
          "value": "{{ $revision }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Application",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      themeColor: '#000080'
      title: New version of an application {{ $name }} is up and running.
  template.app-health-degraded: |
    email:
      subject: Application {{ $name }} has degraded.
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{ $name }} has degraded.
      Application details: {{ $argocdUrl }}/applications/{{ $name }}.
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link": "{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#f4c030",
          "fields": [
          {
            "title": "Health Status",
            "value": "{{ $healthStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Health Status",
          "value": "{{ $healthStatus }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |
        [{
          "@type":"OpenUri",
          "name":"Open Application",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      themeColor: '#FF0000'
      title: Application {{ $name }} has degraded.
  template.app-sync-failed: |
    email:
      subject: Failed to sync application {{ $name }}.
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}}  The sync operation of application {{ $name }} has failed at {{ $finishedAt }} with the following error: {{ $message }}
      Sync operation details are available at: {{ $argocdUrl }}/applications/{{ $name }}?operation=true .
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link":"{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#E96D76",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{ $syncStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ $syncStatus }}"
        },
        {
          "name": "Failed at",
          "value": "{{ $finishedAt }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Open Operation",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}?operation=true"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      themeColor: '#FF0000'
      title: Failed to sync application {{ $name }}.
  template.app-sync-running: |
    email:
      subject: Start syncing application {{ $name }}.
    message: |
      The sync operation of application {{ $name }} has started at {{ $startedAt }}.
      Sync operation details are available at: {{ $argocdUrl }}/applications/{{ $name }}?operation=true .
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link":"{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#0DADEA",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{ $syncStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ $syncStatus }}"
        },
        {
          "name": "Started at",
          "value": "{{ $startedAt }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Open Operation",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}?operation=true"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      title: Start syncing application {{ $name }}.
  template.app-sync-status-unknown: |
    email:
      subject: Application {{ $name }} sync status is 'Unknown'
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{ $name }} sync is 'Unknown'.
      Application details: {{ $argocdUrl }}/applications/{{ $name }}.
      {{if ne .serviceType "slack"}}
      {{if and .app .app.status .app.status.conditions}}
      {{range $c := .app.status.conditions}}
          * {{$c.message}}
      {{end}}
      {{end}}
      {{end}}
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link":"{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#E96D76",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{ $syncStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ $syncStatus }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Open Application",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      title: Application {{ $name }} sync status is 'Unknown'
  template.app-sync-succeeded: |
    email:
      subject: Application {{ $name }} has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{ $name }} has been successfully synced at {{ $finishedAt }}.
      Sync operation details are available at: {{ $argocdUrl }}/applications/{{ $name }}?operation=true .
    slack:
      attachments: |
        [{
          "title": "{{ $name }}",
          "title_link":"{{ $argocdUrl }}/applications/{{ $name }}",
          "color": "#18be52",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{ $syncStatus }}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{ $repoURL }}",
            "short": true
          }
          {{if and .app .app.status .app.status.conditions}}
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          {{end}}
          ]
        }]
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ $syncStatus }}"
        },
        {
          "name": "Synced at",
          "value": "{{ $finishedAt }}"
        },
        {
          "name": "Repository",
          "value": "{{ $repoURL }}"
        }
        {{if and .app .app.status .app.status.conditions}}
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{ $argocdUrl }}/applications/{{ $name }}?operation=true"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default"
            {{if and .repo .repo.RepoURLToHTTPS}}
            ,"uri":"{{$repoURL | call .repo.RepoURLToHTTPS}}"
            {{end}}
          }]
        }]
      themeColor: '#000080'
      title: Application {{ $name }} has been successfully synced
  trigger.on-created: |
    - description: Application is created.
      oncePer: app.metadata.name
      send:
      - app-created
      when: "true"
  trigger.on-deleted: |
    - description: Application is deleted.
      oncePer: app.metadata.name
      send:
      - app-deleted
      when: app.metadata.deletionTimestamp != nil
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState.syncResult.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status
        == 'Healthy'
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-running: |
    - description: Application is being synced
      send:
      - app-sync-running
      when: app.status.operationState.phase in ['Running']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']