apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  {{- $name := "{{ .app.metadata.name }}" }}
  {{- $syncStatus := "{{ .app.status.sync.status }}" }}
  {{- $repoURL := "{{ .app.spec.source.repoURL }}" }}
  {{- $startedAt := "{{ .app.status.operationState.startedAt }}" }}
  {{- $finishedAt := "{{ .app.status.operationState.finishedAt }}" }}
  {{- $message := "{{ .app.status.operationState.message }}" }}
  {{- $revision := "{{ .app.status.sync.revision }}" }}
  {{- $argocdUrl := "{{ .context.argocdUrl }}" }}
  {{- $healthStatus := "{{ .app.status.health.status }}" }}

  context: |
    argocdUrl: "https://iris-argocd.co"

  service.webhook.telegram_webhook: |
    url: $telegramUri
    headers:
    - name: Content-Type
      value: application/json

  template.app-sync-succeeded: |
    webhook:
      telegram_webhook:
        method: POST
        body: |
          {
            "chat_id": -1002251325616,
            "text": "Application {{ $name }} has been successfully synced at {{ $finishedAt }}. Sync operation details are available at: {{ $argocdUrl }}/applications/{{ $name }}?operation=true",
            "message_thread_id": 2
          }

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']